### ISSUE TITLE
Record profiling sessions from the command line

### ISSUE THREAD

**Issue by eskatos** [visualvm/visualvm.src#17]
It would be awesome if we could invoke VisualVM from the command line to automate the recording of profiling sessions and then open the dump for inspection in the VisualVM UI at a later time.

Would such a feature be possible? What kind of changes would it take?

**Comment by mfevzikorkutata** [comment]
Hi,
I am looking for this feature, too. Is it possible to trigger profiling options with below commdan line parameter?

 --enable <arg1>...<argN>  Enable modules for specified codebase names

**Comment by eskatos** [comment]
@thurka, @jisedlac, any comment on this?

I have a little bit of experience with Netbeans RCP and I'm willing to look into contributing if that's something you would be interested in and could provide some guidance.

**Comment by jisedlac** [comment]
Thanks for the feedback! Since VisualVM is a visual tool, we don't have any plans to provide command line features.

The feature you're requesting could be implemented as a standalone profiling library saving the results into a .nps or .npss file, which can be later opened in VisualVM. A good start for writing the command line profiler could be http://wiki.netbeans.org/FitnessViaCLITimeLine .

**Comment by eskatos** [comment]
Interesting! Thanks, I'll have a look.

**Comment by eskatos** [comment]
Closing as won't fix
